### ISSUE TITLE
Screech homepage

### ISSUE THREAD

**Issue by Looky1173** [screech-org/www#2]

**Comment by Weredime** [comment]
cc @LankyBox02 once you're ready feel free to make a PR

**Comment by lankybox02** [comment]
@Weredime help
![image](https://user-images.githubusercontent.com/104015308/172427803-1339f4b6-1a8f-4f87-bec5-155562413052.png)

**Comment by lankybox02** [comment]
Okay so i rebuilt the entire app because i dont know how to adapt onto the old one
![image](https://user-images.githubusercontent.com/104015308/172434325-bc911a16-f2ad-4841-afd4-3897acbf386f.png)

**Comment by lankybox02** [comment]
is it THAT NECCESSARY TO USE SVELTEKIT LIKE IVE BEEN STRUGGLIG FOR AN HOUR TRYING TO GET ONE SINGLE APP TO WORK

**Comment by JaydenDev** [comment]
chill

**Comment by lankybox02** [comment]
sorry i have anger issues

**Comment by lankybox02** [comment]
BUT LETS USE FUCKING NDOEJS INSTEAD OF THIS gFGSDASF

**Comment by lankybox02** [comment]
> Copying HTML/CSS directly from the Scratch website is both not very fun, and dangerous.

???

**Comment by lankybox02** [comment]
what

**Comment by lankybox02** [comment]
> ![image](https://user-images.githubusercontent.com/92550746/172441228-cdf23755-6ebb-45f5-acc5-ec371996430d.png) identical to how it would look on Scratch (copied CSS)

Compare the fucking css. I built it myself. Seriously do you think i am a fucking dumbass that does not know what trademarking or copyright is

**Comment by lankybox02** [comment]
it looks absolutely nothing like on scratch the padding is diferrent the border color is different because i built it from 0

**Comment by lankybox02** [comment]
fucking dumbass

**Comment by lankybox02** [comment]
shut the fuck up

**Comment by lankybox02** [comment]
im gonna cry

**Comment by lankybox02** [comment]
my pc just shut down bc i hit it

**Comment by lankybox02** [comment]
im on my phone

**Comment by JaydenDev** [comment]
Sorry if that sounded rude, didn't mean it that way.

**Comment by lankybox02** [comment]
I'm trying to boot it up and its not working l

**Comment by lankybox02** [comment]
its plugged on

**Comment by lankybox02** [comment]
i fucking hate everyone

**Comment by lankybox02** [comment]
I tried running sveltekit and failed after an hour and a half trying. Here is the raw HTML & CSS:

**Navigation bar**
```
<div class="navbar">
<img src="https://scratch.mit.edu/images/logo_sm.png" />
<li>
	Create
</li>
<li>
	Explore
</li>
<li>
	Ideas
</li>
<li>
	About
</li>
</div>
```

**Box**
```
<div class="box">
<div class="box-header">
What's happening?
</div>
<div class="box-content" id="activity">
</div>
</div>
```

**CSS**
```
body {
	font-family: Helvetica;
    margin: calc(10px + 10vh);
    margin-top: calc(60px + 10px);
    color: #575e75;
}

.navbar {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    background-color: #4d97ff;
    color: white;
}

.navbar > li {
	display: inline-block;
    list-style-type: none;
    vertical-align: middle;
    font-weight: bold;
    float: left;
    padding: 14px 10px;
    font-size: 17px;
}

.navbar > li:hover {
	cursor: pointer;
	background: rgba(0, 0, 0, 0.2);
}

.navbar > img {
    float: left;
    padding: 8px 12px;
	height: 30px;
    transform: scaleX(-1);
}

.box-header {
	border-top-left-radius: 10px;
	border-top-right-radius: 10px;
    background-color: #f2f2f2;
    padding: 8px 10px;
    border: 1px solid lightgrey;
	font-weight: bold;
}

.box-content {
	border: 1px solid lightgrey;
	border-top: 0;
    padding: 10px;
}
```

**Comment by JaydenDev** [comment]
> I tried running sveltekit and failed after an hour and a half trying. Here is the raw HTML & CSS:
> 
> **Navigation bar**
> 
> ```
> <div class="navbar">
> <img src="https://scratch.mit.edu/images/logo_sm.png" />
> <li>
> 	Create
> </li>
> <li>
> 	Explore
> </li>
> <li>
> 	Ideas
> </li>
> <li>
> 	About
> </li>
> </div>
> ```
> 
> **Box**
> 
> ```
> <div class="box">
> <div class="box-header">
> What's happening?
> </div>
> <div class="box-content" id="activity">
> </div>
> </div>
> ```
> 
> **CSS**
> 
> ```
> body {
> 	font-family: Helvetica;
>     margin: calc(10px + 10vh);
>     margin-top: calc(60px + 10px);
>     color: #575e75;
> }
> 
> .navbar {
>     position: fixed;
>     top: 0;
>     left: 0;
>     right: 0;
>     background-color: #4d97ff;
>     color: white;
> }
> 
> .navbar > li {
> 	display: inline-block;
>     list-style-type: none;
>     vertical-align: middle;
>     font-weight: bold;
>     float: left;
>     padding: 14px 10px;
>     font-size: 17px;
> }
> 
> .navbar > li:hover {
> 	cursor: pointer;
> 	background: rgba(0, 0, 0, 0.2);
> }
> 
> .navbar > img {
>     float: left;
>     padding: 8px 12px;
> 	height: 30px;
>     transform: scaleX(-1);
> }
> 
> .box-header {
> 	border-top-left-radius: 10px;
> 	border-top-right-radius: 10px;
>     background-color: #f2f2f2;
>     padding: 8px 10px;
>     border: 1px solid lightgrey;
> 	font-weight: bold;
> }
> 
> .box-content {
> 	border: 1px solid lightgrey;
> 	border-top: 0;
>     padding: 10px;
> }
> ```

Try removing the '>s' in the they either aren't needed or are causing the code to not run. (Svelte is very picky, the HTML, CSS, and JS must be entirely correct in order for it to work.

**Comment by JaydenDev** [comment]
Try this for the css

```css
body {
	font-family: Helvetica;
    margin: calc(10px + 10vh);
    margin-top: calc(60px + 10px);
    color: #575e75;
}

.navbar {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    background-color: #4d97ff;
    color: white;
}

.navbar li {
	display: inline-block;
    list-style-type: none;
    vertical-align: middle;
    font-weight: bold;
    float: left;
    padding: 14px 10px;
    font-size: 17px;
}

.navbar li:hover {
	cursor: pointer;
	background: rgba(0, 0, 0, 0.2);
}

.navbar img {
    float: left;
    padding: 8px 12px;
	height: 30px;
    transform: scaleX(-1);
}

.box-header {
	border-top-left-radius: 10px;
	border-top-right-radius: 10px;
    background-color: #f2f2f2;
    padding: 8px 10px;
    border: 1px solid lightgrey;
	font-weight: bold;
}

.box-content {
	border: 1px solid lightgrey;
	border-top: 0;
    padding: 10px;
}
```
